Tunning the l_* scripts

diff --git a/Ubuntu-Newton/lib/l_iso2vm b/Ubuntu-Newton/lib/l_iso2vm
--- a/Ubuntu-Newton/lib/l_iso2vm
+++ b/Ubuntu-Newton/lib/l_iso2vm
@@ -63,7 +63,11 @@ start_iso_vm () {
   done
    
   ## Check that the virsh commands work
-  virsh list &> /dev/null || eval $PKG_CMD libvirt-bin $SILENCER
+  #virsh list &> /dev/null || eval $PKG_CMD libvirt-bin $SILENCER
+
+  
+  virsh list &> /dev/null || echo "ERROR: If 'virsh list' does not work, it's probably because you just installed libvirt. Try to restart/relog-in." 
+
   run_or_exit "virsh list"
   run_or_exit "virt-install --version"
 
@@ -170,6 +174,8 @@ else
 fi
 
 #run_or_exit "sudo su $USER -c 'virsh list' | grep $VM_NAME"
+
+
 run_or_exit "echo \"virsh list | grep $VM_NAME\" |bash "
 printf "\033[0;32m   BOMSI started successfully the VM $VM_NAME   :) \n\033[0m" 
 
