Fixed sudo prompt and permissions in .cache/virt-manager

diff --git a/Ubuntu-Ocata/lib/l_opsys b/Ubuntu-Ocata/lib/l_opsys
--- a/Ubuntu-Ocata/lib/l_opsys
+++ b/Ubuntu-Ocata/lib/l_opsys
@@ -65,10 +65,11 @@ fi
 
 ## Checking if "sudo" works for the current user, otherwise add to sudoers
 RES=$(sudo -v -n 2>&1)
-if ! echo "$RES" |grep -q ' a password is required' ;then
+if [ $RES == '' ] || [ "$(echo "$RES" |grep -q ' a password is required')" ];then
   echo "The user '$USER' is not allowed to use sudo. Adding $USER to sudoers"
   VISUDO_LINE="$USER    ALL=(ALL:ALL) NOPASSWD:ALL"
-  su -c "echo \"${VISUDO_LINE}\" >> /etc/sudoers"
+  su -c "echo \"${VISUDO_LINE}\" >> /etc/sudoers" || \
+  exit  1 
 fi
 
 
@@ -152,15 +153,17 @@ if [[ "$INST_PKGS" == *"virt-manager"* ]]; then
   printf "\033[0;33mWARNING: The virt-manager GUI might not work properly until you log again into the system. i.e.: open another terminal.\033[0m\n"
   echo "As a workaround we'll exectute 'su - $USER' and try the bomsi command again"
 
-  ## for some reason this directory has sometimes wrong permissions
-  [ -d "~/.cache/virt-manager" ] && touch ~/.cache/virt-manager/virt-install.log || \
-  echo "We need sudo to change permissions in ~/.cache/virt-manager/" && \
-  eval sudo chown -R $USER ~/.cache/virt-manager/ $SILENCER
   echo ">> Starting the virt-manager GUI"
   echo "This is the first time we run virt-manager, so we'll run it with 'sudo su $USER' to make it work"
   eval sudo su $USER -c virt-manager $SILENCER
  
 fi
+
+
+## for some reason this directory has sometimes wrong permissions
+[ -d "~/.cache/virt-manager" ] && touch ~/.cache/virt-manager/virt-install.log || \
+echo "We need sudo to change permissions in ~/.cache/virt-manager/" && \
+eval sudo chown -R $USER $HOME/.cache/virt-manager/ $SILENCER
 
 
 ## Make sure the user has permission to create VMs
